export enum SelectObservables {
  DRAWER_PLAYLISTS,
  DRAWER_QUEUE,
  ROUTE_ALBUM,
  ROUTE_ARTIST_MOST_PLAYED_TRACKS,
  ROUTE_ARTIST_POPULAR_TRACKS,
  ROUTE_ARTIST_RECENT_TRACKS,
  ROUTE_ARTIST_RELEASES,
  ROUTE_CHARTS,
  ROUTE_NOW_PLAYING,
  ROUTE_PLAYLIST,
  ROUTE_PLAYLISTS,
  ROUTE_SEARCH,
}
