export enum SelectObservables {
  ROUTE_ALBUM,
  ROUTE_ARTIST_MOST_PLAYED_TRACKS,
  ROUTE_ARTIST_POPULAR_TRACKS,
  ROUTE_ARTIST_RECENT_TRACKS,
  ROUTE_ARTIST_RELEASES,
  ROUTE_NOW_PLAYING,
  ROUTE_PLAYLIST,
  ROUTE_PLAYLISTS,
  ROUTE_SEARCH,
  UI_QUEUE,
}
